### ISSUE TITLE
Error: update.json文件不存在或格式错误

### ISSUE THREAD

**Issue by zl3one6** [Fndroid/shadowsocks-update#1]
I follow the readme and create the update.json file under the shadowsocks directory. When I run the 'ssu' command in the shadowsocks directory, it consoles out the error "update.json文件不存在或格式错误". I try to open the cmd in administration mode, it still has the same issue.

**Comment by Fndroid** [comment]
``update.json`` must be a legal JSON format file.

Please provide your ``update.json`` file with fake provider urls.

**Comment by zl3one6** [comment]
The content in my update.json is 

```
{
    "providers": [
        https://www.boslife.co/downloads/conf/xxxxx.conf
    ],
    "filter": [
        "sz",
        "sh",
        "tsuenwan"
    ]
}
```
Thanks

**Comment by Fndroid** [comment]
urls must be wrapped by ``""``

**Comment by zl3one6** [comment]
Thank you. That is my carelessness.
